"""Exact JUnit identities that support each retained replay assertion."""

REPLAY_ASSERTION_CASES = {
    "bambu": {
        "wire_receive_only": ("tests.hardware_certification.test_wire_replay", "test_bambu_tls_mqtt_replay_runs_live_passive_worker_and_v2_parser"),
        "idle_state": ("tests.hardware_certification.test_wire_replay", "test_protocol_live_worker_proves_idle_state[bambu]"),
        "printing_state": ("tests.hardware_certification.test_wire_replay", "test_protocol_live_worker_proves_printing_state[bambu]"),
        "production_parser": ("tests.hardware_certification.test_passive_observers", "test_bambu_observer_requires_two_v2_samples_and_reports_ams_capability"),
        "closed_active_transport": ("tests.hardware_certification.test_active_transports", "test_bambu_active_transport_emits_only_exact_certification_payloads"),
        "active_state_machine": ("tests.hardware_certification.test_active_exercise", "test_bambu_live_session_runs_real_v2_parser_mqtt_and_ftps_workflow"),
        "fault_matrix": ("tests.hardware_certification.test_passive_observers", "test_protocol_unknown_enum_and_extra_field_policy[bambu]"),
        "freshness_boundary": ("tests.hardware_certification.test_passive_observers", "test_protocol_repeated_payload_cannot_prove_freshness[bambu]"),
        "payload_boundary": ("tests.hardware_certification.test_wire_replay", "test_bambu_and_elegoo_oversize_payloads_fail_closed"),
        "authentication_boundary": ("tests.hardware_certification.test_wire_replay", "test_bambu_authentication_failure_is_bounded"),
        "disconnect_boundary": ("tests.hardware_certification.test_wire_replay", "test_protocol_disconnect_fails_after_bounded_retry[bambu]"),
        "reconnect_boundary": ("tests.hardware_certification.test_wire_replay", "test_protocol_reconnect_succeeds_once_and_records_provenance[bambu]"),
    },
    "elegoo": {
        "wire_receive_only": ("tests.hardware_certification.test_wire_replay", "test_elegoo_loopback_peer_runs_live_passive_worker_without_client_frames"),
        "idle_state": ("tests.hardware_certification.test_wire_replay", "test_protocol_live_worker_proves_idle_state[elegoo]"),
        "printing_state": ("tests.hardware_certification.test_wire_replay", "test_protocol_live_worker_proves_printing_state[elegoo]"),
        "production_parser": ("tests.hardware_certification.test_passive_observers", "test_elegoo_observer_correlates_attributes_with_two_unsolicited_status_frames"),
        "closed_active_transport": ("tests.hardware_certification.test_active_transports", "test_elegoo_active_transport_uses_only_reviewed_sdcp_codes"),
        "active_state_machine": ("tests.hardware_certification.test_active_exercise", "test_elegoo_live_session_runs_real_parser_and_websocket_action_workflow"),
        "fault_matrix": ("tests.hardware_certification.test_passive_observers", "test_protocol_unknown_enum_and_extra_field_policy[elegoo]"),
        "freshness_boundary": ("tests.hardware_certification.test_passive_observers", "test_protocol_repeated_payload_cannot_prove_freshness[elegoo]"),
        "payload_boundary": ("tests.hardware_certification.test_wire_replay", "test_bambu_and_elegoo_oversize_payloads_fail_closed"),
        "disconnect_boundary": ("tests.hardware_certification.test_wire_replay", "test_protocol_disconnect_fails_after_bounded_retry[elegoo]"),
        "reconnect_boundary": ("tests.hardware_certification.test_wire_replay", "test_protocol_reconnect_succeeds_once_and_records_provenance[elegoo]"),
    },
    "moonraker": {
        "wire_receive_only": ("tests.hardware_certification.test_wire_replay", "test_moonraker_loopback_peer_runs_live_passive_worker_with_exact_gets"),
        "idle_state": ("tests.hardware_certification.test_wire_replay", "test_protocol_live_worker_proves_idle_state[moonraker]"),
        "printing_state": ("tests.hardware_certification.test_wire_replay", "test_protocol_live_worker_proves_printing_state[moonraker]"),
        "production_parser": ("tests.hardware_certification.test_passive_observers", "test_moonraker_observer_uses_real_parser_and_two_bounded_queries"),
        "closed_active_transport": ("tests.hardware_certification.test_active_transports", "test_moonraker_active_transport_has_closed_paths_and_remote_name"),
        "active_state_machine": ("tests.hardware_certification.test_active_exercise", "test_moonraker_live_session_runs_real_parser_and_http_action_workflow"),
        "fault_matrix": ("tests.hardware_certification.test_passive_observers", "test_protocol_unknown_enum_and_extra_field_policy[moonraker]"),
        "freshness_boundary": ("tests.hardware_certification.test_passive_observers", "test_protocol_repeated_payload_cannot_prove_freshness[moonraker]"),
        "payload_boundary": ("tests.hardware_certification.test_wire_replay", "test_http_protocol_oversize_and_unavailable_endpoints_fail_closed[moonraker]"),
        "authentication_boundary": ("tests.hardware_certification.test_wire_replay", "test_http_passive_wire_rejects_redirect_malformed_oversize_and_auth"),
        "disconnect_boundary": ("tests.hardware_certification.test_wire_replay", "test_protocol_disconnect_fails_after_bounded_retry[moonraker]"),
        "reconnect_boundary": ("tests.hardware_certification.test_wire_replay", "test_protocol_reconnect_succeeds_once_and_records_provenance[moonraker]"),
    },
    "prusalink": {
        "wire_receive_only": ("tests.hardware_certification.test_wire_replay", "test_prusalink_loopback_peer_runs_live_passive_worker_with_exact_gets"),
        "idle_state": ("tests.hardware_certification.test_wire_replay", "test_protocol_live_worker_proves_idle_state[prusalink]"),
        "printing_state": ("tests.hardware_certification.test_wire_replay", "test_protocol_live_worker_proves_printing_state[prusalink]"),
        "production_parser": ("tests.hardware_certification.test_passive_observers", "test_prusalink_observer_combines_status_and_job_without_retaining_raw_payload"),
        "closed_active_transport": ("tests.hardware_certification.test_active_transports", "test_prusalink_only_exposes_atomic_upload_start_and_numeric_job_paths"),
        "active_state_machine": ("tests.hardware_certification.test_active_exercise", "test_prusalink_live_session_runs_real_parser_and_http_action_workflow"),
        "fault_matrix": ("tests.hardware_certification.test_passive_observers", "test_protocol_unknown_enum_and_extra_field_policy[prusalink]"),
        "freshness_boundary": ("tests.hardware_certification.test_passive_observers", "test_protocol_repeated_payload_cannot_prove_freshness[prusalink]"),
        "payload_boundary": ("tests.hardware_certification.test_wire_replay", "test_http_protocol_oversize_and_unavailable_endpoints_fail_closed[prusalink]"),
        "authentication_boundary": ("tests.hardware_certification.test_wire_replay", "test_prusalink_authentication_failure_is_bounded"),
        "disconnect_boundary": ("tests.hardware_certification.test_wire_replay", "test_protocol_disconnect_fails_after_bounded_retry[prusalink]"),
        "reconnect_boundary": ("tests.hardware_certification.test_wire_replay", "test_protocol_reconnect_succeeds_once_and_records_provenance[prusalink]"),
    },
}
