apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odin-demo-data
  namespace: odin-demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odin-demo-heartbeat
  namespace: odin-demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
  storageClassName: longhorn
